### ISSUE TITLE
Indexer uses multiple threads even when a single thread is specified.

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#114]
Here I've modified my Writer#put to print `Thread.current`:

``` ruby
  def put(context)
    puts "Sleeping #{Thread.current}"
    sleep 10
    puts "Awake"
  end
```

```
2015-08-10T13:01:17-05:00  INFO    Indexer with 1 processing threads, reader: Traject::MarcReader and writer: ObjectFactoryWriter
Sleeping #<Thread:0x007fc46e24bde8>
Sleeping #<Thread:0x007fc4640c0410>
Awake
Awake
```

You can see they are different threads.

**Comment by jrochkind** [comment]
Can you provide a complete reproduction project?

**Comment by jcoyne** [comment]
I don't think there is any need for that. Stick that debug ^ in any Writer#put method and run a batch of records through. You will see it's running in multiple threads.  If you want it to actually be single threaded you can do:

```
  provide "processing_thread_pool", 0
```

But that seems a little bit counter intuitive.

**Comment by jrochkind** [comment]
Okay, I did seem to duplicate with this:

~~~
require 'traject/mock_reader'

class ::ThreadPrintingNoOpWriter
  def initialize(settings)
  end

  def put(context)
    puts "Writing record #{context.position} in thread: #{Thread.current.object_id}"
  end

  def close
  end
end

settings do
  provide "reader_class_name", "Traject::MockReader"
  provide "writer_class_name", "ThreadPrintingNoOpWriter"
  provide "mock_reader.limit", 200 # default is 10_000

  provide "processing_thread_pool", 1
end
~~~

outputs:

~~~
Writing record 1 in thread: 70361803717980
Writing record 2 in thread: 70361803717980
Writing record 3 in thread: 70361803717980
Writing record 7 in thread: 70361790415360
Writing record 4 in thread: 70361803717980
Writing record 5 in thread: 70361803717980
Writing record 10 in thread: 70361790415360
Writing record 6 in thread: 70361803717980
~~~

Note record 10 (which also comes sort of out of order) is in a different thread, indeed. 

I see only two distinct threads in use -- does that match your observations, @jcoyne?

I think what's going on is:

1 processing thread in the thread pool, in addition to the 1 thread used for reading. So two threads total in the app, one used for reading, one used for processing. 

In what cases would the writer wind up writing on the 'reader' thread?  If the reader is reading faster than than processing/writing can keep up (which is surprising in this reproduction, but may somehow be happening?) -- then eventually the queue for the 1-thread pool fills up.  And we have configured the thread pool with "run in calling thread" behavior as a form of back pressure. 

I think this is pretty good default behavior. 

But perhaps we need to document better than processing_thread_pool=1 still means a separate thread for processing, in addition to the reading thread, and `0` means not a thread pool at all? Any suggestions on where/how to document this?

Or perhaps we need to make the ThreadPool itself configurable so you could give it an infinite work queue if you wanted to potentially use all that RAM queing up work in cases where the reader is reading faster than processing/writing can take place?  I'm not sure if there are any cases anyone would want to do that. 

Do you want to say any more about your use case in which the fact that it wound up writing on the 'calling' reading thread was a problem?

**Comment by jcoyne** [comment]
The service I was writing to was not thread safe.  I assumed the message I was seeing "Indexer with 1 processing threads," was saying I wasn't using multiple threads.  Then I found that I had a number of concurrency bugs to work out.  I would say just removing the message and saying "set threads to zero to do indexing an a single thread" in the docs is sufficient.  I still think that's a bit weird because there is one thread working when I set it to zero threads.

**Comment by jrochkind** [comment]
Any suggestions to where in the docs to put "set threads to zero to do indexing an a single thread"  where someone would notice? 

Here's what the [docs say already](https://github.com/traject/traject/blob/master/doc/settings.md):

> processing_thread_pool Number of threads in the main thread pool used for processing records with input rules. On JRuby or Rubinius, defaults to 1 less than the number of processors detected on your machine. On other ruby platforms, defaults to 1. Set to 0 or nil to disable thread pool, and do all processing in main thread.

That could be more clear, but not sure if anyone will see it there?

Traject was designed to be multi-threaded -- when you set processing_thread_pool to `1`, there is 1 of what we consider a 'processor' thread in a thread pool with 1 thread in it, but this is in addition to the one primary reader thread -- and in cases of 'back pressure' the processing may happen on that thread too. (Some of the writers also use thread pools of their own, the `processing_thread_pool` setting is definitely not a maximum of all threads that may be used by a pipeline, but only for the 'processing' phase). 



There are cases where 1 processing_thread_pool is what you want, it should generally result in faster throughput, even under MRI, than setting processor threads to 0. 

Perhaps for cases where you want to force everything to really for sure be in one single thread, we should add a new global setting, which would force all Traject::ThreadPool's to have a `0` thread count, meaning not really a thread pool at all always execute in calling thread.  That would allow a failsafe way to say "really, I don't want any threads, anywhere", and would effect Writers that may use thread pools as well, or anywhere else that may use thread pools.  That would be a global setting effecting the entire process though. Anyone have an opinion on whether that might be a good idea? BillDeuber?

**Comment by jrochkind** [comment]
I think this behavior is already correct. Setting `processing_thread_pool` to `1` means one _indexing/processing_ thread, but still one additional reader thread.  Which is something one might want, and should be possible behavior. Setting indexing threads to `0` means no additional threads for indexing/processing, just the one reader thread (or, depending on the nature of the reader, could be more reader threads, but that's up to the reader). 

Architecture where reader threads are separate from processing threads is appropriate and good I think; these steps are strictly encapsulated and don't really know about each other or how many threads each is using. (_Writers_ can also hypothetically use threads of their own). 

could use better documentation/announcement, but I'm not sure where/how.  Perhaps the output "Indexer with 1 processing threads" should say "...plus reader thread(s)".  Or perhaps the name of the config `processing_thread_pool` should be different?   Or perhaps there should be a config `strict_single_thread` which all readers/writers/indexers should somehow respect?

I'm inclined to say behavior is fine as is and no changes needed, but curious as to other opinions. @billdueber ?

**Comment by jrochkind** [comment]
There is better documentation on this, as well as some new methods that will hopefully make programmatic use cases like I _think_ @jcoyne's easier, in 3.0.  

Please feel free to see docs at https://github.com/traject/traject/blob/79172935e8775462e9d5c92497dc99113f26c035/doc/programmatic_use.md , part of PR #156. 

Closing this for now, but continued feedback is very welcome.
