### ISSUE TITLE
solr 5 and 6 SolrException: missing content stream

### ISSUE THREAD

**Issue by farooqsadiq** [traject/traject#158]
We encounter an error in solr 5.5 and solr 6.6 which is caused by an empty payload when testing the /update URL in  Traject::SolrJsonWriter::derive_solr_update_url_from_solr_url

This can be resolved by adding  {"commit" => 'true'}  to the @http_client.get(candidate) call.
I would be happy to make a pull request for this change, if this is an acceptable fix.

**Comment by jrochkind** [comment]
Sure, PR would be great, thanks!  Do you think that will cause any problems with earlier versions of solr? I don't _think_ so, but I don't entirely understand what's going on.

**Comment by farooqsadiq** [comment]
I tested the /update with adding {"commit" => 'true'} added on solr-4.3. It works the same, so I do not think it will cause any issues with earlier versions of solr.

**Comment by jrochkind** [comment]
Closed by #159
