### ISSUE TITLE
Remove marc4j and don't cut a specific jruby gem

### ISSUE THREAD

**Issue by billdueber** [traject/traject#185]
(Sorry to respond here -- access to slack is weird at this airport for some reason)

The case to package marc4j reader with `traject` hasn't existed for me for a while -- ruby-marc is "fast enough" for the general case, and for that matter I don't actually use any standard marc formats (I'm stuck with alephsequential on the one hand and choose to use marc-json for the Hathitrust stuff). So long as we don't do anything that *breaks* jruby (such as moving to a concurrency library that doesn't use actual threads, which I can't imagine happening) I don't see a compelling reason to cut a specific jruby release. 

@jrochkind I'm assuming you're all about this, right?

**Comment by jrochkind** [comment]
@billdueber already done number 2 in #187.  Although the Marc4J reader is still default, it's no longer a dependency, there's no longer a separate JRuby gem -- you've got to add the dependency yourself if you're using the default. 

Do you want to go further and make it no longer the default? Is the Marc4JReader not actually enough of an advantage to try to push it on people like this?

**Comment by jrochkind** [comment]
Closed by #187
