### ISSUE TITLE
(prospective) documentation for running traject with truffleruby

### ISSUE THREAD

**Issue by adjam** [traject/traject#196]
This is *NOT* a bug report against traject. I decided to see if it works under a new JVM(-ish) based Ruby implementation, and I'm just recording it in the hopes it helps others who may also be heading down this unfinished road.  

All this was encountered with a project that pulls traject 2.3.4 into its Gemfile.  It installs and runs under MRI 2.4.x and 2.5.1, and JRuby 9.2.0.0.

Truffleruby 1.0.0-rc5, was installed with `ruby-install` and selected via `chruby`.  Installation hangs for a long time, but does complete eventually.

One tip: per https://github.com/oracle/truffleruby/issues/62 if your project's `Gemfile` includes `nokogiri` you should run `bundle config build.nokogiri --use-system-libraries` before you run `bundle install` -- this will compile nokogiri support using the native `libxml2` bindings.

You will need to make sure you have the `devel` versions of `libxml2` and `libxslt` installed first. (e.g. `libxml2-dev` for debian linux derivatives or `libxml2-devel` for Red Hat/Fedora derivatives)   

I encountered significant hangs while running `bundle install` on my project, it takes a long time (> 4 minutes) but it did eventually complete.  Running with `bundle -V install` appears to indicate that truffleruby is particularly slow running benchmarks, I think?
```
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/.gitignore
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/.travis.yml
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/.yardopts
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/CHANGES.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/Gemfile
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/LICENSE.txt
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/README.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/Rakefile
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/bench/bench.rb
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/bin/traject
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/doc/batch_execution.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/doc/extending.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/doc/indexing_rules.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/doc/other_commands.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/doc/settings.md
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/index_bench/batch.dat
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/index_bench/common.rb
/home/theuseraccount/.gem/truffleruby/2.4.4/gems/traject-2.3.4/index_bench/index_bench.rb
<long pause>
```
Good luck!

**Comment by adjam** [comment]
No, it's not ready for production yet -- I would be surprised if they release it before it works reliably with Rails, but working with it in the state it's in is the only way it will ever get there.  It bears mentioning that the implementation here (as installed by `ruby-install` v0.7.0)  is the "Native" one, not the "JVM" one, btw.  Yes, fetching stuff over HTTP is not its strong point at the moment, and bundler has other issues: https://github.com/oracle/truffleruby/issues/1398  -- the numbers reported in that issue, though, are not in line with what I'm seeing but this is an anecdote not data.

As far as "producing results" goes, it's speed-and quality-comparable to MRI 2.5.1 on the stuff I've tried it on so far, not that I have done detailed investigations into either.

**Comment by jrochkind** [comment]
Cool. I don't know why your `bundle install` results are so slow, but I am 99.9% sure it has nothing to do with traject! 

If you use the 3.0.0.alpha.2 release though, the traject gem source won't include that large index_bench.rb file.

**Comment by jrochkind** [comment]
closing, but this closed issue will still be there for anyone searching. we can re-later if we have more. I believe none of the instructions above are traject-specific, they are just general advice for using truffle-ruby at this point, or using truffle-ruby with nokogiri.
