### ISSUE TITLE
Namespaces of record inside a extract_xpath block

### ISSUE THREAD

**Issue by bibliotechy** [traject/traject#197]
I was a little confused that the record passed to block was not already able to use the default namespaces. For example:

I define my namespaces in my config file 

```
settings do
  provide "nokogiri.namespaces", {
    "oai_qdc" => "http://worldcat.org/xmlschemas/qdc-1.0/",
    "dcterms" => "http://purl.org/dc/terms/",
    "oai" => "http://www.openarchives.org/OAI/2.0/",
    "dc" => "http://purl.org/dc/elements/1.1/",
    "oai_dc" => "http://www.openarchives.org/OAI/2.0/oai_dc/"
  }
provide "nokogiri.each_record_xpath", "//record"
end
```
Then I run an `extract_path` to get titles, but because I work in a library, I have to do weird stuff like add the name of the collection the item belongs to to the title if `dcterms:isPartOf` is present. I would expect to be able to run something like:

```
to_field "title_display", extract_xpath("//dc:title") do |rec, acc|
  partOf = rec.xpath("//dcterms:isPartOf")&.first&.text
  acc.map! {|title| "#{title}; part of #{partOf}" } unless partOf.nil?
end
```

but that throws an exception because the record object doesn't know about the namespaces we defined in traject.

```
Exception: Nokogiri::XML::XPath::SyntaxError: ERROR: Undefined namespace prefix: //dcterms:isPartOf
    /Users/cbn/.rvm/gems/ruby-2.5.1@traject3/gems/nokogiri-1.8.4/lib/nokogiri/xml/searchable.rb:198:in `evaluate'
```
I end up needing to pass in `default_namespaces` every time I call `xpath` on the record object. 

```
to_field "title_display", extract_xpath("//dc:title") do |rec, acc|
  partOf = rec.xpath("//dcterms:isPartOf", default_namespaces)&.first&.text
  acc.map! {|title| "#{title}; part of #{partOf}" } unless partOf.nil?
end
```

This might just be a documentation issue, but it seems like there might be a more intuitive way to include the namespaces into the record object so users don't need that `default_namespaces` every time.

**Comment by bibliotechy** [comment]
Yeah, I was realizing it was just a standard issue with Nokogiri documents, not with traject itself, but I did wonder if there is something we could do.

For example, we could add the namespace definitions to the root of each record in the `extract_xpath` method. 

```ruby
  def extract_xpath(xpath, ns: {}, to_text: true)
      ...
        lambda do |record, accumulator|

          namespaces.each {|k,v| record.root.add_namespace_definition(k,v)}
          result = record.xpath(xpath)
          
          if to_text
      ...
```

I've tried that out on [this branch](https://github.com/traject/traject/commit/cc419723774f525bc6f7c2c4511690d8e7c933c4) and it works for my use case defined above.

Alternatively, we could inject the namespaces somewhere in the `NokogiriReader.each` method before the `child_doc` is yielded. https://github.com/traject/traject/blob/master/lib/traject/nokogiri_reader.rb#L92-L100 . I've not tried that yet, but it seems like it could be more general.

**Comment by jrochkind** [comment]
I'm kind of shocked that calling Nokogiri's `add_namespace_definition` works to do what you want -- I thought that would actually _change the XML doc_ (which I'm not fond of), but I was pretty sure it would _not_ eliminate the need to still reference the namespaces in the nokogiri `xpath`. I thought nokogiri _always_ required namespaces.  Are you really sure it works?  I'll try to find time to play around with it some! 

Another alternative, avoiding any mutation of the nokogiri doc, would be not delivering an actual Nokogiri::XML::Document at all, but a special Traject::XML::Document which wraps a Nokogiri::XML::Document -- but delegates all method calls to the underlying document, _except for_ the querying methods, where it supplies the default namespaces before the equivalent of calling 'super'. 

But I think that might have bad performance implications, in addition to just being kind of heavy-weight. 

I wonder if even the add_namespaces approach has performance implications. Do you feel like benchmarking?

Yet another approach.  Traject, or even you in your project locally, could just provide an `xpath(doc, path)` method (not OO, taking the record as first arg), which just calls `doc.path`, but passes in default_namespaces as the second arg. :)

I want to explore add_namespaces a bit more, cause I'm _shocked_ that they work how you say! :)  But I'm not super optimistic about using it -- I've found nokogiri's namespace mutation methods to be weird and sometimes not doing what's expected, and with performance problems when done on a massive scale.

**Comment by jrochkind** [comment]
Here's the docs for Nokogiri `add_namespace_definition`. 

https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri%2FXML%2FNode:add_namespace_definition

Nothing there would lead me to believe they'd let you use namespaces in queries without passing in the mapping -- it says "The result is as if parsed XML for this node had included an attribute 'xmlns:prefix=value'" -- but if the XML for that node had included that, ordinarily nokogiri would _still_ make you pass in namespace mappings on query!  So.... weird if it's different for you! I wonder if it's possible it's actually a nokogiri bug that it does what you want?!?

**Comment by jrochkind** [comment]
Aha, nokogiri does have special handling for namespaces registered on the root, in querying.

> To make this namespace registration a bit easier, nokogiri will automatically register any namespaces it finds on the root node for you.

http://www.nokogiri.org/tutorials/searching_a_xml_html_document.html#namespaces

This is something you could probably force yourself if you wanted, have the first rule in your traject config be:

```ruby
each_record do |record|
  namespaces.each {|k,v| record.root.add_namespace_definition(k,v)}
end
```

I'm still curious about the performance implications. And I don't like that this would be actually _changing_ the XML doc -- if you were to choose to serialize out `record` to xml, you would not get the same text after doing this as before. I'm not sure if you'd always get XML with the same semantics or not.

**Comment by bibliotechy** [comment]
I agree that mutating the original XML could have unforeseen consequences.

The `each_record`seems workable, and better than forcing the behavior on everyone.

One other idea I this triggered was that `extract_xpath` could take something like `:inject_namespaces` as an option and then it would only happen for the records I want to happen for, not necessarily for every record.

**Comment by jrochkind** [comment]
Closing for now, although I agree it's not an ideal situation, none of the possible solutions seem great to me, so for now this is it.
