### ISSUE TITLE
Jruby builds are failing due to nokogiri 1.9.0+ namespace regression

### ISSUE THREAD

**Issue by jcoyne** [traject/traject#203]
Due to bundler compatibility issues. See https://travis-ci.org/traject/traject/builds/496132319?utm_source=github_status&utm_medium=notification

**Comment by jcoyne** [comment]
After fixing the bundler problem, we now have a nokogiri incompatiblity.

**Comment by jrochkind** [comment]
I've had lots of trouble with nokogiri xml namespace support in jruby. Sounds like a new nokogiri release may have introduced new  bugs (I wonder as a side-effect of _fixing_ some other bugs I reported!). 

In an ideal world we'd isolate and identify the bugs and report to nokogiri. 

Alternately/additionally-as-a-stopgap, we could have jruby tests intentionally test with an older nokogiri, basically say we only have jruby compatibility with certain version of nokogiri (cause apparently that's what we already had?). 

The bundler compat issues are probably entirely orthogonal, but can probably be fixed a different way than allowing bundler 2 -- instead _forcing_ bundler 1. There are a bunch of bugs in a botched bundler 2 release that make this all very confusing, but we don't necessarily have to test under bundler 2 if we don't want to, and there are ways around it. 

Any thoughts or interests?

**Comment by jrochkind** [comment]
I suspect it's a nokogiri issue. 

The build failing with namespace-related issues in #204 is using nokogiri 1.10.1

The previous last green build seems to be at https://travis-ci.org/traject/traject/builds/440694267, and the Java builds were using nokogiri 1.8.5. 

I am going to try to reproduce locally and figure out exactly what nokogiri version breaks it, as first step.

**Comment by jrochkind** [comment]
Reproduced locally with bundler 1.16.3 (sanity check that it does not require upgrading to bundler 2.0 to reproduce), and jruby 9.2.0.0. 

using nokogiri 1.9.0 (java) reproduces failing tests. 

using nokogiri 1.8.5 (java) does not reproduce, all tests are green. 

So some change in nokogiri 1.9.0 release causes our tests to fail. Want to isolate and report to nokogiri. 

If we are able to rewrite code to pass tests on nokogiri 1.9, it might make it fail on nokogiri 1.8. If so, might increase traject dependency requirements, with such a release, to nokogiri 1.9. Anyone see any problem with that?

**Comment by jrochkind** [comment]
Isolated and reported to nokogiri: https://github.com/sparklemotion/nokogiri/issues/1875
