### ISSUE TITLE
Publication Date in marc21_semantics.rb should fall back to 260c or 264c

### ISSUE THREAD

**Issue by ksprague25** [traject/traject#224]
The publication_date method in /macros/marc21_semantics.rb should fall back to either the 260c or the 264c as the source for a publication date.  

The 264 is new the RDA, Library of Congress approved tag for publication information, and newer records at most institutions will record it there instead of the 260: https://www.loc.gov/marc/bibliographic/bd264.html.  Older records, however, will still use the 260 tag for publication information, so both need to be checked for a date if the 008 does not contain date information.

**Comment by jrochkind** [comment]
Cool, the traject logic may have been written before 264 existed, or was in common use. 

Wow, the current logic is kind of convoluted. https://github.com/traject/traject/blob/master/lib/traject/macros/marc21_semantics.rb#L323

Would you be interested in submitting a pull-request with feature and ideally a test, @ksprague25 ?  

You may have already figured out how to get your local logic to do what you want even though the `publication_date` macro alone does not -- but if you haven't, I'm happy to give you tips.

**Comment by ksprague25** [comment]
It’s on my to-do list!  Targeting mid-May after the end of semester.
