### ISSUE TITLE
Unauthorized failure when solr server has basic auth enabled.

### ISSUE THREAD

**Issue by dkinzer** [traject/traject#230]
There is currently no way to configure basic auth for solr requests.   We recently ran into this issue when we enabled basic auth for some of our solrcloud instances.

Currently the work around is to create our own instance of `HTTPClient` and configure the basic auth settings for that client then override the default client with the one we've configured the way we do here: tulibraries/cob_az_index#6.

It would be nice to be able to set this via configuration instead of having to override the default writer.

**Comment by jrochkind** [comment]
So we just need one or more settings for the basic auth username/password?

Interested in sending a PR?

**Comment by dkinzer** [comment]
@jrochkind yes,  we would need a setting for the username and password and just use them to configure basic auth for the client.

I'd be happy to send a PR for this.
