### ISSUE TITLE
allow indexing configuration from included modules

### ISSUE THREAD

**Issue by ebenenglish** [traject/traject#237]
It would be very helpful if it were possible to define `Traject::Indexer` configuration indexing steps in modules that are included into an `Indexer` class, similar to the way that an `Indexer` can inherit configuration from its [superclass](https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L208-L210).

This feature would allow indexing steps to be shared between objects that respond to the same properties. It would also allow complex indexing to be broken into component modules for easier code maintenance.

It _is_ currently possible to set configuration in an included module, like so:
```ruby
module SomeIndexerBehavior
  extend ActiveSupport::Concern
  included do
    configure do
      to_field 'text_field_tsi', literal('foo')
    end
  end
end
```
When that module is include in an `Indexer` class, the `to_field 'text_field_tsi'` is successfully added to the `@index_steps` ivar for the `Indexer`.

```ruby
class MyIndexer < Traject::Indexer
  include SomeIndexerBehavior
end
```
```
irb> MyIndexer.new 
=> #<MyIndexer:0x0000563914c2f3a0 @writer_class=nil, @completed=false, @settings={}, 
     @index_steps=[(to_field "text_field_tsi" at (pry):11)], @after_processing_steps=[]>
```

However, if there is a `configure` block defined in `MyIndexer`, it will _override_ the included module:
```ruby
class MyOtherIndexer < Traject::Indexer
  include SomeIndexerBehavior
  configure do
    to_field 'string_field_ssi', literal('bar')
  end
end
```
```
irb> MyOtherIndexer.new
=> #<MyOtherIndexer:0x0000563914a3d970 @writer_class=nil, @completed=false, 
    @settings={}, @index_steps=[(to_field "string_field_tsi" at (pry):22)],
    @after_processing_steps=[]>
```

I'm not sure how difficult it would be to support this? I _think_ it's essentially the same as allowing an `Indexer` to have multiple `configure` blocks in the same class, as in:
```ruby
class YetAnotherIndexer < Traject::Indexer
  configure do
    to_field 'string_field_ssi', literal('bar')
  end
  configure do
    to_field 'facet_field_ssi', literal('baz')
  end
end
```
Currently only the last `configure` block is applied:
```
irb> YetAnotherIndexer.new
=> #<YetAnotherIndexer:0x0000563913afa6e8 @writer_class=nil, @completed=false, 
    @settings={}, @index_steps=[(to_field "facet_field_ssi" at (pry):31)], 
    @after_processing_steps=[]>
```
Thanks!

**Comment by jrochkind** [comment]
Thanks for the write-up! 

I would have expected this to work already, I'm surprised it does not, will have to look into it. 

Ah, wait, I think it's probably got to do with the hack to make the class-level `configure` work at all -- it was kind of a hack, since originally traject written for command-line use had all configuration done on a particular _instance_ not a class. 

I bet we can fix it, let me take a look.

**Comment by jrochkind** [comment]
Oh yeah, I see. The class-level configure stuff is kind of a hack on top of a design that didn't anticipate it. https://github.com/traject/traject/pull/213#issuecomment-474065478

It gets superclass configure through kind of a weird means. https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L207-L209

But here's why calling `configure` more than once on the same class overwrites itself:
https://github.com/traject/traject/blob/master/lib/traject/indexer.rb#L203

We can fix it by making that an array that gets added to... it is making the kind of hacky architecture even more hacky, but it should work.

**Comment by ebenenglish** [comment]
That would be awesome, thanks!
