### ISSUE TITLE
extract_xpath is not working for nokogiri xml attributes.

### ISSUE THREAD

**Issue by dkinzer** [traject/traject#241]
`extract_path` fails to extract attribute using an attribute path.

For the following example XML:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
  <responseDate>2020-03-03T04:16:09Z</responseDate>
  <request verb="ListRecords" metadataPrefix="marc21" set="blacklight" from="2020-03-02T20:47:11Z">https://na02.alma.exlibrisgroup.com/view/oai/01TULI_INST/request</request>
  <ListRecords>
    <record>
      <header status="deleted">
        <identifier>oai:alma.01TULI_INST:991025803889703811</identifier>
        <datestamp>2020-03-03T03:54:35Z</datestamp>
        <setSpec>blacklight</setSpec>
        <setSpec>rapid_print_journals</setSpec>
        <setSpec>blacklight_qa</setSpec>
      </header>
    </record>
  </ListRecords>
</OAI-PMH>
```

Trying to extract the the status attribute fails

```
 to_field "status", extract_xpath("//oai:record/oai:header/@status")
 # status = [""]
```

Issue was found in traject-v3.3.0

Here is a link to a failing test gist: https://gist.github.com/dkinzer/88f44606986a2cb787f78fc6f60d0035

**Comment by jrochkind** [comment]
Very odd!  Thanks for the report!

I would like to look into this, but am at code4lib and on vacation next week, so might not be able to get to it until after that. If I forget about it after next week and you haven't heard back, please feel free to comment again to trigger a notification to remind me, thanks!

**Comment by dkinzer** [comment]
@jrochkind Yes, in the linked test I provide a test for the "vanilla nokogiri" behavior.  And that one works as expected.

**Comment by jrochkind** [comment]
Hey @dkinzer , noticed this getting back to it!

I'm not sure if I'd consider this a bug, or a missing feature/feature request. But even if the latter, we should probably be able to accomodate it. 

In the meantime, here's one workaround way to do what you want:

    to_field "status", extract_xpath("//oai:record/oai:header", to_text: false), transform( ->(element) { element["status"] })

**Comment by jrochkind** [comment]
@dkinzer any interest in testing and/or code reviewing #245?

**Comment by dkinzer** [comment]
@jrochkind, sure I'll take a look at that later today.

**Comment by jrochkind** [comment]
3.4.0 released including this improvement.
