### ISSUE TITLE
Example on how to process and XML file

### ISSUE THREAD

**Issue by hectorcorrea** [traject/traject#264]
I wanted to add a small but complete example on how to parse an XML file (https://gist.github.com/hectorcorrea/59fa5854ce6f9ee1a4b86a23fea5f108) but I am not sure if this is something you are interested in and/or where to put such example. 

This would be to complement the notes already existing in [xml.md](https://github.com/traject/traject/blob/master/doc/xml.md) 

Any thoughts?

**Comment by jrochkind** [comment]
Sure, sounds good! 

Your example has a config file that's only 10 lines or so, would it make sense to actually embed it in xml.md?

But I think you want to put these files somewhere. Make an ./examples/xml directory? Link to it from xml.md using relative URL link in markdown?
