### ISSUE TITLE
Processing MARC XML files without namespaces

### ISSUE THREAD

**Issue by hectorcorrea** [traject/traject#266]
The library services platform [Alma](https://exlibrisgroup.com/products/alma-library-services-platform/) that claims to be "the fastest growing cloud-based library services platform" apparently does not know how to include namespaces in the MARC XML files that it produces. This results in files that looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<collection>
 <record>
    ...
  </record>
</collection>
```

As opposed to files that look like:

```
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns="http://www.loc.gov/MARC21/slim" xmlns:marc="http://www.loc.gov/MARC21/slim">
 <record>
    ...
  </record>
</collection>
```
 
The files without the namespace cannot be parsed out of the box by Traject when using the `-t xml` parameter. Without the namespaces Traject does not recognize the records inside the XML file.

Could it be possible to include a parameter or another reader in Traject to handle this automatically?

Ideally Alma should not produce invalid XML files, but given its preponderance it might make sense to handle the issue in Traject. 

@tpendragon came up with a solution by creating an [AlmaReader class](https://github.com/pulibrary/marc_liberation/blob/alma/marc_to_solr/lib/alma_reader.rb) and [setting up in the config.rb](https://github.com/pulibrary/marc_liberation/blob/alma/marc_to_solr/lib/traject_config.rb#L22) file that could be used as the basis to handle this natively in Traject.

**Comment by jrochkind** [comment]
While I love the idea of traject handling alma marc, unfortunately, looking at the code for traject... all the MarcXML reading is all embedded in ruby-marc. So the change would have to happen there... and knowing what I know of ruby-marc, and some legacy architectural choices in there which haven't been touched in a long time, it would be a bit messy to do. :(

A completely separate Alma reader is definitely one way to do it. I don't know if it makes sense to bundle with traject or not. How awful does it seem to make a separate gem with just that, and point to it from traject readme? If that seems tortuous, I guess it's not the end of the world to just bundle it with traject if there's demand for it?

**Comment by hectorcorrea** [comment]
Yeah, I think another gem would be an overkill. Perhaps just a note in the documentation (is there a Wiki for Traject?) would be good enough.

**Comment by jrochkind** [comment]
A note in the documentation pointing to that class in PUL's code? Would people just be expected to copy-and-paste the code from PUL, basically everyone having their own fork?  

I mean, it's better than having to re-invent the wheel, certainly! I guess it's up to y'all Alma users to organize however you like.

**Comment by jrochkind** [comment]
Looking at that actual PUL code... it actually monkey-patches some internal private implementations in ruby-marc classes. Normally I would say this is a fairly "risky" thing to do likely to break in future ruby-marc implementations, but I guess if ruby-marc isn't getting much attention it's less likely to change and break it. ¯\_(ツ)_/¯

But yeah, I wouldn't actually want that code in traject (or a third-party gem), it's not very safe code, it's kind of a hack. 

But whatever works for y'all Alma people, not my problem! 

I also realize looking at that code that I'm confused about what's going on, I don't really understand the nature of the problem or data in the first place, i am curious to see an Alma MarcXML export. Now I realize I'm not sure if it's really the Alma export that violates standards, or a bug in ruby-marc?  Would be curious to see an Alma MarcXML export example, and also to hear from anyone that's looked into it what they think is going on, whether it's an Alma bug or a ruby-marc bug or what.
