### ISSUE TITLE
Add equivalent feature to Traject::TranslationMap but for lists

### ISSUE THREAD

**Issue by dkinzer** [traject/traject#278]
Now that we are adding a way to filter out values from the accumulated values it would be nice to have a similar feature to the `Traject::TranslationMap` but for lists that can be passed into the `select` or `delete_if` macros.

This is useful because like with translation maps, the task of maintaining  the list can be done by a non developer and it's much more convenient to have them making PRs against a simple text file than a file full of other code.

**Comment by dkinzer** [comment]
In one of our use cases we'll need to convert such a list to a regex that can be passed into `delete_if`.  Considering that use case, I'm no longer certain it makes sense to make this a general feature.

**Comment by jrochkind** [comment]
Yeah, regexp from a textfile, hmm. 

Either way, it might make sense to start out implementing it in your local app -- I think it should hopefully be pretty smooth and frictionless to implement as a local "add-on" feature, I think?  Then if it works out well, we could move it to traject?

**Comment by billdueber** [comment]
@dkinzer I'm still having trouble picturing the use case -- you're saying it'd be something like 

```
any_match = Regexp.union(File.open('myfile.txt').to_a.map(&:chomp).map{|x| Regexp.escape(x)})
matches_myfile = ->(str) { any_match.match?(str) }
```

...and then pass `maches_myfile` to, e.g., `delete_if`?

**Comment by dkinzer** [comment]
@billdueber I'm working on a PR  for one of our project.  I'll link to this issue once it's ready.  I don't know if it's really an issue yet.  I'm working through it now and I have some ideas to nicely circumvent some of the issues that I think are present.

**Comment by dkinzer** [comment]
So implemented a basic version of this at https://github.com/tulibraries/cob_index/pull/31.

@billdueber I think the idea of the regex is to make the delete_if by values  case insensitive.

**Comment by jrochkind** [comment]
we could just have a case-insensitive flag to delete_if... but that's harder now that we've generalized it to procs, it wouldn't work there! I dunno. 

Traject means to make it *really* easy to add your own custom "macros" too, there is nothing wrong with you writing exactly what you need. If we discover multiple people needing similar stuff, we can always put it in traject then.

**Comment by billdueber** [comment]
I'm still confused by the logic of `filter`. Naming is hard. Could do `only_if_in` and `unless_in` and then take anything that implements `#include?`. I like this better because then whatever logic needs to happen (e.g., case-insensitivity) is the responsibility of the object passed to the macro.

So in this case, the `load_list` (or a specialization) is where the "work" would happen determining what type of object to produce (a Set? Array? Hell, could be database calls). The interface of the filtering macros is just "something that implements `#include`". 

```ruby
class CIList
  def initialize(*args)
    @values = Set.new(Array[args].map(&:downcase))
  end
  
  def add(val)
    @values << val.downcase
  end

  def include?(val)
   @values.include?(val.downcase)
 end
end
```

Side note: you probably don't want to build up your regexp by hand with `join('|')`. Use [Regexp.union](https://ruby-doc.org/core-2.4.1/Regexp.html#method-c-union).

**Comment by dkinzer** [comment]
@billdueber the logic for the naming is that `delete_if` already exists in Ruby and therefore makes sense to use it instead of filter.  The current implementation would accept any input that can accepts `include` but also `===` which means at least `Array`, `Set`, `proc`, `lambda`, `Regexp`.

This would work `delete_if(/(Hello|world)/ix)`; which would delete "hello", or "world"  values from acc disregarding case.  This too would would work but not disregarding case `delete_if(["hello", "world"])`.

With regards to the `load_list_file` utility method that this specific issue is about, I don't think it needs to be concerned about returning a regex anymore because on further though, I believe that behavior is more natural to be in Array (similar to `.to_s`, `to_json` ... etc).

So in my local app I'm monkey patching `Array` with a core extension module and I'm able to do this:

`delete_if(load_list_file("foo").to_regex)`... where a file located in the path ` lib/lists/foo.txt` has the following structure:

```
Hello
World
```

The group assigned to curate this list would merely be concerned with CRUD-ing the contents of that file.

**Comment by dkinzer** [comment]
@jrochkind  RE:

    If I was writing something to match case-insenstively, I wouldn't bother with that regexp rigamarole, I'd just do thing.downcase == other_thing.downcase or something like that.

Yeah, that makes sense.  But if you have an `Array.to_regex` method available to any array then it's not much of an issue.
