### ISSUE TITLE
provide a single-jar package?

### ISSUE THREAD

**Issue by jrochkind** [traject/traject#59]
It is theoretically to package up a jruby package, including the jruby runtime and all gem dependencies, in a single jar.  I have considered that since the very first traject, as a possible way to ease installation for non-rubyists.  At first, I think Bill didn't think it was neccesary, but I think 'getting jruby installed and figuring out how to use it' has been shown to sometimes be a barrier to adoption. 

Would 'single jar file' (basically the same installation model as SolrMarc) effectively meet this need?

https://github.com/jruby/warbler/issues/297

**Comment by billdueber** [comment]
We could still potentially go this route, bundling up all the jruby-specific stuff (marc4j and solrj) into one big file, but I'm not sure we'll be gaining much over telling people to just install the appropriate gems. I think we should close this.

**Comment by jrochkind** [comment]
I think it actually would be gaining a lot (even without the jruby-specific stuff) -- the point is that you don't need to install anything, not even a ruby version (let alone deal with chruby/rvm/whatever), you just need java (which you already have), you download a .jar file, it just works. 

Makes it a lot more accessible to the non-rubyist. 

However, the fact that traject 2.0 will run in any ruby (does not require jruby anymore) lowers the barriers for use anyway. 

However howerver, you still need jruby for performance. 

But I'm not in a hurry to do this either. I'm sort of waiting and seeing if there's demand. But if we release 2.0 and _still_ can't get hardly anyone to use traject, I'd reconsider trying this. 

Can we just leave this ticket hanging around open, as an advertisement for people interested in it to tell us so?

**Comment by billdueber** [comment]
Given how hard it is to produce such a jar (by which I mean "trivially easy"), there's no reason we shouldn't go ahead and provide one. There must be an automated way to keep up with dependent-gem updates we can tap into, right?

**Comment by jrochkind** [comment]
There are a couple things I'd want to figure out -- like how someone using such a jar COULD use additional gems not packaged with the jar if they wanted to, maybe.  But just generally think through different scenarios and try them out and make sure there's a good way to make it so. Which I don't feel like doing so much immediately honestly. 

Also I'd want to build some deploy tools for it, so every time we did a release a .jar automatically got built AND packaged up as a github release artifact, etc. 

Alternately, I suppose we could release a .jar as an experimental we-don't-promise-to-do-this-again release for people to try out and give us feedback. 

If I understand what you mean by "keep up with dependent-gem updates", there's nothing to be done -- just run `bundle update` before you build the .jar, and it will include the most recent versions of all gems available that meet your gemspec.  If you mean a way for a user of the jar to do it in between jar releases -- I think they're probably out of luck.

**Comment by jrochkind** [comment]
If you mean a way to automatically notice that we the maintainers need to release a new .jar because there are new versions of dependencies that need to be packaged with it -- or even go so far as to automatically release the jar with the new bundled dependencies (.jar 2.0.0.2 or whatever, 2.0.0 traject code, but with udpated dependencies included) -- there probably IS a way to do that, but it'd be some work that might end up useless if nobody wants the .jar anyway haha.

**Comment by jrochkind** [comment]
I still find this idea intriguing, but there hasn't actually been a lot of demand for it, so closing for now.
