### ISSUE TITLE
get leader out in a MarcExtractor spec?

### ISSUE THREAD

**Issue by jrochkind** [traject/traject#89]
Does it make sense to make MarcExtractor support leader after all?

If so, in theory I'd prefer some string like "LEADER" to extract the leader, than "000".  But it may be worthwhile to use "000" just because that's what SolrMarc does, and that's what some other MARC-using software does too (but not all software, and it's not part of any spec, just a de factor convention some software uses).  

"LDR" would be another option. 

Any thoughts?  

(I do _not_ think this is a pre-req for 2.0, at all). 

In theory, just about any three-letter ([0-9a-zA-Z]) string at all _could_ be a MARC tag. (And theoretically, even a different length string, although I'm not sure any common MARC variants do that). The leader isn't really a tag at all in the MARC spec. Is part of my hesitance to use any any string at all that theoretically could conflict with a real tag to mean 'leader', and why I'd prefer a non-three-letter string like LEADER if done at all.  But practicality and de facto conventions maybe should trump theoretical soundness here.

**Comment by billdueber** [comment]
On the one hand, the list of times you might use the leader is...well, there's probably only the one, or maybe two. On the other hand, if we're going to get take-up from the solrmarc community, it shouldn't have an obvious "well, traject can't do that as easily" moment. 

We lean pretty heavily on the MARC::Field interface, so this will be a little more screwing around than I originally thought. I think we should probably just go with 'LDR' as a tag; it makes it similar to solrmarc, and it's probably true that use of the leader is going to be a lot more common than records with an actual 'LDR' field. 

I'll take a look at it today and see if I can figure out a quasi-elegant way to do it; otherwise target 2.1?

**Comment by billdueber** [comment]
So, the annoying part is going to be inserting a control-field-like leader object in the right place so things don't come out of order. Right now we rely on `MARC::Record#fields(array,of,tags)`, but of course that won't give us the leader. Ugh.

**Comment by jrochkind** [comment]
I would not insert a mock control-field-like leader object. Can't we just put a special case in the _parser_, to use completely different logic if tag is `LDR` -- just grab the leader in that case, don't go through the MARC::Field stuff at all?  Or are there performance concerns?

**Comment by billdueber** [comment]
It's a matter of getting the data in the correct order (e.g, for
"008[3-4]:245a:LDR[3-7]" the leader data should be the third item in the
values array). Right now we use
`record.fields([list,of,tags,we're,interested,in])` to get the fields in
the order we want, but we'll need to re-work that logic to put the leader
in where we want it.

I'm 70% of the way there now; I'll have a pull request tonight, I think.


On Mon, Feb 16, 2015 at 2:35 PM, Jonathan Rochkind <notifications@github.com
> wrote:

> I would not insert a mock control-field-like leader object. Can't we just
> put a special case in the *parser*, to use completely different logic if
> tag is LDR -- just grab the leader in that case, don't go through the
> MARC::Field stuff at all? Or are there performance concerns?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/traject-project/traject/issues/89#issuecomment-74561210>
> .
>



-- 
Bill Dueber
Library Systems Programmer
University of Michigan Library

**Comment by jrochkind** [comment]
Bah, honestly if it significantly complexifies the code, that significantly dampers my enthusiasm for it. I think there are very very few use cases where it actually makes sense to put a leader in a spec with other tags like this -- honestly, I'm not even sure it really does for the inherited SolrMarc case (you're putting a byte from the 008 and the leader together in the same list and then running them all through the same translation map? It works, but it's pretty messy)

**Comment by jrochkind** [comment]
I think I'm deciding this isn't actually neccesary (and may not be desirable), for how little one needs a leader, and we'll just close this for now?
