### ISSUE TITLE
Make CommandLine more suitable for embedded use

### ISSUE THREAD

**Issue by jrochkind** [traject/traject#98]
Command line currently writes things (usage, error messages) to console, and `exit`s on fatal error. 

It would be convenient to make these configurable, to make it more suitable for embedded use.

**Comment by billdueber** [comment]
Do you think the solution is to expose the command line, or to better expose the settings from the indexer? If we had something like:

```ruby

indexer = Traject::Indexer.new
indexer.load_file(filename)
indexer.settings do
  provide "key", "value"
  provide "key", "value"
end

indexer.process(filename_or_handle)
```

...that would get us much of the way there, yes?

**Comment by jrochkind** [comment]
I think both maybe?. 

I believe you already CAN do everything in your code example -- sometimes with slightly different API than you provided, but rarely more complicated API. Mainly it needs better documentation in Indexer. 

I think it would probably be useful, though, in addition, for instance for embedding in a rake task, to be able to do:

     CommandLine.new("-c", "conf/file.rb", "name_of_marc.mrc").execute

For embedding in a rake task, I think that might actually be the most convenient API.  For other uses, you might want to use an Indexer directly -- which I think you actually CAN already do fairly conveniently, it just needs better docs with examples. 

I can do that part first, if that seems more useful? 

~~~
indexer = Traject::Indexer.new

# THIS api doesn't, exist...
indexer.load_file(filename)
# But this already does, and isn't so much worse...
indexer.instance_eval(File.open(pathname).read, pathname)

# You can do this already:
indexer.settings do
  provide "key", "value"
  provide "key", "value"
end

# You can do this already if you pass a handle, not a filename. 
indexer.process(filename_or_handle)
# But easy enough to get a handle:
indexer.process(File.open(filename))
~~~

So I think the API already supported by Indexer is actually probably good enough already (or very very close to it) -- it does need to be doc'd with examples of how you might use it though.

**Comment by jrochkind** [comment]
I guess providing a:

~~~ruby
# May raise if file does not exist or is not readable
def load_config_file(pathname)
     self.instance_eval(File.open(pathname), pathname)
end
~~~

May be an improvement for direct indexer use, in 3-5 lines, ha. That might be worth doing. But in general, I think Indexer already has the right API, the docs (class header docs) just need examples to guide people. 

I can write those first if you think that's got more beneift than making CommandLine configurable to raise instead of `exit` and write to a log instead of $stderr?

**Comment by jrochkind** [comment]
I added better example/instructions for programmatic use of Indexer under current code, in comments at ec931c170. 

I think just having it doc'd improves things quite a bit. 

I think I tend to agree with you that focusing on the API for Indexer is better than trying to make CommandLine more suitable for embedded use. The right programmatic API is ruby OO, not `CommandLine.new("-c", "path/to/config.rb")` or `CommandLine.new("-c path/to/config.rb")`. 

So I'll close this ticket now?  If someone (including one of us) comes along with a use case where it really would make sense to use CommandLine over Indexer API, I'd change my mind of course!

The sharpest point in the current Indexer API is probably the raw `instance_eval`. We have issue #99 to discuss that
